# Generated by Django 4.0.2 on 2022-02-14 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('divers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited', models.BooleanField()),
                ('favorite', models.BooleanField()),
                ('bucket_list', models.BooleanField()),
                ('comments', models.CharField(max_length=300)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='site',
            name='marine_life',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.AddField(
            model_name='review',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='divers.site'),
        ),
    ]
