# Generated by Django 4.0.2 on 2022-02-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divers', '0002_review_alter_site_marine_life_delete_log_review_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comments',
            field=models.CharField(default='', max_length=300),
        ),
    ]
